services:
  portfolio-web:
    image: http-portfolio:latest
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.50"
          memory: 1GB
        reservations:
          cpus: "0.25"
          memory: 256M
    ports:
      - "7681:7681"
    stdin_open: true
    tty: true
